18:45:52 INFO GitHub token rate limit: Rate(reset=2025-04-01 19:09:55+00:00, remaining=4653, limit=5000)
18:49:19 INFO Waiting for model:
  test-u6xod43w/0 [executing] active: 
18:49:49 INFO Waiting for model:
  test-u6xod43w/0 [idle] active: 
18:50:00 INFO Wait for condition not met, sleeping 10
18:50:43 INFO Waiting for model:
  test-u6xod43w/0 [executing] maintenance: Reconciling runners
18:51:14 INFO Waiting for model:
  test-u6xod43w/0 [idle] active: 
18:51:19 INFO File content of /var/log/github-runner-metrics.log: {"timestamp": 1743533311.0, "event": "runner_installed", "flavor": "test-u6xod43w", "duration": 139.0}
{"timestamp": 1743533404.0, "event": "runner_start", "flavor": "test-u6xod43w", "workflow": "Workflow Dispatch Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "idle": 93.0, "queue_duration": 2.0}
{"timestamp": 1743533407.0, "event": "runner_stop", "flavor": "test-u6xod43w", "workflow": "Workflow Dispatch Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "status": "normal", "job_duration": 3.0, "job_conclusion": "success"}
{"timestamp": 1743533442.5630639, "event": "reconciliation", "flavor": "test-u6xod43w", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 28.702638864517212}
{"timestamp": 1743533462.9892774, "event": "reconciliation", "flavor": "test-u6xod43w", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 19.358440160751343}
18:51:24 INFO Model status:

Model                            Controller           Cloud/Region         Version  SLA          Timestamp
test-charm-metrics-success-7wzw  github-pr-e884d-lxd  localhost/localhost  3.6.4    unsupported  18:51:24Z

App                                   Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder-u6xod43w           active      1  github-runner-image-builder  latest/edge   68  no       
test-u6xod43w                                  active      1  github-runner                               0  no       

Unit                                     Workload  Agent  Machine  Public address  Ports  Message
github-runner-image-builder-u6xod43w/0*  active    idle   0        10.240.222.80          
test-u6xod43w/0*                         active    idle   1        10.240.222.18          

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.240.222.80  juju-018aa5-0  ubuntu@22.04      Running
1        started  10.240.222.18  juju-018aa5-1  ubuntu@22.04      Running

18:51:24 INFO Juju error logs:

machine-0: 18:25:08 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 18:25:08 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-u6xod43w-0: 18:25:08 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-github-runner-image-builder-u6xod43w-0: 18:25:45 ERROR unit.github-runner-image-builder-u6xod43w/0.juju-log Pipx command failed, code: 1, out: None, err: None
machine-1: 18:29:02 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 18:29:02 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-u6xod43w-0: 18:29:02 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-test-u6xod43w-0: 18:50:32 ERROR unit.test-u6xod43w/0.juju-log Unable to get SSH connection for instance test-u6xod43w-0-n-2951a62c3464, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 106, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 297, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u6xod43w-0-n-2951a62c3464, key path: /home/runner-manager/.ssh/test-u6xod43w-0-n-2951a62c3464.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-u6xod43w-0-n-2951a62c3464
unit-test-u6xod43w-0: 18:50:35 ERROR unit.test-u6xod43w/0.juju-log Unable to get SSH connection for instance test-u6xod43w-0-n-2951a62c3464, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 106, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 297, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u6xod43w-0-n-2951a62c3464, key path: /home/runner-manager/.ssh/test-u6xod43w-0-n-2951a62c3464.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-u6xod43w-0-n-2951a62c3464
unit-test-u6xod43w-0: 18:50:37 ERROR unit.test-u6xod43w/0.juju-log Failed to get SSH connection while removing test-u6xod43w-0-n-2951a62c3464
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 335, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 106, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 297, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u6xod43w-0-n-2951a62c3464, key path: /home/runner-manager/.ssh/test-u6xod43w-0-n-2951a62c3464.key
unit-test-u6xod43w-0: 18:50:39 ERROR unit.test-u6xod43w/0.juju-log Invalid pulled metrics. No runner_installed information for test-u6xod43w-0-n-2951a62c3464.
unit-test-u6xod43w-0: 18:50:42 ERROR unit.test-u6xod43w/0.juju-log Unable to get SSH connection for instance test-u6xod43w-0-n-2951a62c3464, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 106, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 297, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u6xod43w-0-n-2951a62c3464, key path: /home/runner-manager/.ssh/test-u6xod43w-0-n-2951a62c3464.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-u6xod43w-0-n-2951a62c3464
unit-test-u6xod43w-0: 18:50:46 ERROR unit.test-u6xod43w/0.juju-log Unable to get SSH connection for instance test-u6xod43w-0-n-2951a62c3464, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 106, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 297, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u6xod43w-0-n-2951a62c3464, key path: /home/runner-manager/.ssh/test-u6xod43w-0-n-2951a62c3464.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-u6xod43w-0-n-2951a62c3464
unit-test-u6xod43w-0: 18:50:51 ERROR unit.test-u6xod43w/0.juju-log Unable to get SSH connection for instance test-u6xod43w-0-n-2951a62c3464, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 106, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 297, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u6xod43w-0-n-2951a62c3464, key path: /home/runner-manager/.ssh/test-u6xod43w-0-n-2951a62c3464.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-u6xod43w-0-n-2951a62c3464
unit-test-u6xod43w-0: 18:50:51 ERROR unit.test-u6xod43w/0.juju-log Failed to get SSH connection while removing test-u6xod43w-0-n-2951a62c3464
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 335, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 106, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u6xod43w-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 297, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u6xod43w-0-n-2951a62c3464, key path: /home/runner-manager/.ssh/test-u6xod43w-0-n-2951a62c3464.key
unit-test-u6xod43w-0: 18:50:53 ERROR unit.test-u6xod43w/0.juju-log Invalid pulled metrics. No runner_installed information for test-u6xod43w-0-n-2951a62c3464.
unit-test-u6xod43w-0: 18:50:53 ERROR unit.test-u6xod43w/0.juju-log No metrics returned after deleting test-u6xod43w-0-n-2951a62c3464

18:51:24 INFO Forgetting model main...