18:50:50 INFO Waiting for model:
  test-ldrjzaab/0 [executing] active: 
18:51:20 INFO Waiting for model:
  test-ldrjzaab/0 [idle] active:
18:54:09 INFO Waiting for model:
  test-ldrjzaab/0 [executing] active: 
18:54:39 INFO Waiting for model:
  test-ldrjzaab/0 [idle] active: 
18:54:49 INFO Wait for condition not met, sleeping 30
18:55:31 INFO [TEST SETUP] Run command pkill -9 run.sh on test-ldrjzaab-0-n-7ee5fd1fbcd8
18:55:31 WARNING dict_values([[{'version': 4, 'addr': '10.145.193.119', 'OS-EXT-IPS:type': 'fixed', 'OS-EXT-IPS-MAC:mac_addr': 'fa:16:3e:c5:57:22'}]])
18:55:32 WARNING ssh_cmd: su - ubuntu -c 'ssh -i /home/runner-manager/.ssh/test-ldrjzaab-0-n-7ee5fd1fbcd8.key -o "StrictHostKeyChecking no" ubuntu@10.145.193.119 pkill -9 run.sh'
18:55:33 INFO Run command 'pkill -9 run.sh' in runner with result 0: 'None' 'Warning: Permanently added '10.145.193.119' (ED25519) to the list of known hosts.
'
18:55:36 INFO Runner test-ldrjzaab-0-n-7ee5fd1fbcd8 status: online
18:55:36 INFO Runner still marked as online, waiting for it to be marked offline
18:57:04 INFO Waiting for model:
  test-ldrjzaab/0 [executing] active: 
18:57:34 INFO Waiting for model:
  test-ldrjzaab/0 [idle] active: 
18:57:36 INFO File content of /var/log/github-runner-metrics.log: {"timestamp": 1746125449.168556, "event": "reconciliation", "flavor": "test-ldrjzaab", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 14.318034648895264}
{"timestamp": 1746125466.5913715, "event": "reconciliation", "flavor": "test-ldrjzaab", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 16.079161643981934}
{"timestamp": 1746125626.1949134, "event": "reconciliation", "flavor": "test-ldrjzaab", "crashed_runners": 0, "idle_runners": 1, "active_runners": 0, "expected_runners": 1, "duration": 125.64965581893921}
{"timestamp": 1746125647.9502912, "event": "reconciliation", "flavor": "test-ldrjzaab", "crashed_runners": 0, "idle_runners": 1, "active_runners": 0, "expected_runners": 1, "duration": 20.449345350265503}
{"timestamp": 1746125670.326459, "event": "reconciliation", "flavor": "test-ldrjzaab", "crashed_runners": 0, "idle_runners": 1, "active_runners": 0, "expected_runners": 1, "duration": 21.00572943687439}
{"timestamp": 1746125603.0, "event": "runner_installed", "flavor": "test-ldrjzaab", "duration": 87.0}
{"timestamp": 1746125693.0, "event": "runner_start", "flavor": "test-ldrjzaab", "workflow": "Workflow Dispatch Crash Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "idle": 90.0, "queue_duration": 3.0}
{"timestamp": 1746125733.0, "event": "runner_stop", "flavor": "test-ldrjzaab", "workflow": "Workflow Dispatch Crash Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "status": "abnormal", "status_info": {"code": 137}, "job_duration": 40.0, "job_conclusion": "cancelled"}
{"timestamp": 1746125823.2760751, "event": "reconciliation", "flavor": "test-ldrjzaab", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 22.41513180732727}
{"timestamp": 1746125839.8897073, "event": "reconciliation", "flavor": "test-ldrjzaab", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 15.318077325820923}
18:57:38 INFO Model status:

Model                            Controller           Cloud/Region         Version  SLA          Timestamp
test-charm-metrics-failure-pi6i  github-pr-b51b1-lxd  localhost/localhost  3.6.5    unsupported  18:57:38Z

App                                   Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder-ldrjzaab           active      1  github-runner-image-builder  latest/edge   68  no       
test-ldrjzaab                                  active      1  github-runner                               0  yes      

Unit                                     Workload  Agent  Machine  Public address  Ports     Message
github-runner-image-builder-ldrjzaab/0*  active    idle   0        10.131.164.122            
test-ldrjzaab/0*                         active    idle   1        10.131.164.165  8080/tcp  

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.131.164.122  juju-642f25-0  ubuntu@22.04      Running
1        started  10.131.164.165  juju-642f25-1  ubuntu@22.04      Running

18:57:39 INFO Juju error logs:

machine-0: 18:26:57 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 18:26:57 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-ldrjzaab-0: 18:26:57 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 18:27:03 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 18:27:03 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-ldrjzaab-0: 18:27:03 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-github-runner-image-builder-ldrjzaab-0: 18:27:43 ERROR unit.github-runner-image-builder-ldrjzaab/0.juju-log Pipx command failed, code: 1, out: None, err: None
unit-test-ldrjzaab-0: 18:27:47 ERROR unit.test-ldrjzaab/0.juju-log Command python3 -m pip uninstall github_runner_manager failed with code 2: b'ERROR: Exception:\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper\n    status = _inner_run()\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run\n    return self.run(options, args)\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/uninstall.py", line 106, in run\n    uninstall_pathset = req.uninstall(\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_install.py", line 723, in uninstall\n    uninstalled_pathset.remove(auto_confirm, verbose)\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_uninstall.py", line 364, in remove\n    if auto_confirm or self._allowed_to_proceed(verbose):\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_uninstall.py", line 404, in _allowed_to_proceed\n    return ask("Proceed (Y/n)? ", ("y", "n", "")) != "n"\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/misc.py", line 227, in ask\n    response = input(message)\nEOFError: EOF when reading a line\n'
unit-test-ldrjzaab-0: 18:49:31 ERROR unit.test-ldrjzaab/0.juju-log Unable to get SSH connection for instance test-ldrjzaab-0-n-5e6be518f048, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-ldrjzaab-0-n-5e6be518f048, key path: /home/runner-manager/.ssh/test-ldrjzaab-0-n-5e6be518f048.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-ldrjzaab-0-n-5e6be518f048
unit-test-ldrjzaab-0: 18:49:33 ERROR unit.test-ldrjzaab/0.juju-log Unable to get SSH connection for instance test-ldrjzaab-0-n-5e6be518f048, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-ldrjzaab-0-n-5e6be518f048, key path: /home/runner-manager/.ssh/test-ldrjzaab-0-n-5e6be518f048.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-ldrjzaab-0-n-5e6be518f048
unit-test-ldrjzaab-0: 18:49:36 ERROR unit.test-ldrjzaab/0.juju-log Failed to get SSH connection while removing test-ldrjzaab-0-n-5e6be518f048
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 311, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-ldrjzaab-0-n-5e6be518f048, key path: /home/runner-manager/.ssh/test-ldrjzaab-0-n-5e6be518f048.key
unit-test-ldrjzaab-0: 18:49:40 ERROR unit.test-ldrjzaab/0.juju-log Invalid pulled metrics. No runner_installed information for test-ldrjzaab-0-n-5e6be518f048.
unit-test-ldrjzaab-0: 18:49:43 ERROR unit.test-ldrjzaab/0.juju-log Unable to get SSH connection for instance test-ldrjzaab-0-n-5e6be518f048, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-ldrjzaab-0-n-5e6be518f048, key path: /home/runner-manager/.ssh/test-ldrjzaab-0-n-5e6be518f048.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-ldrjzaab-0-n-5e6be518f048
unit-test-ldrjzaab-0: 18:49:47 ERROR unit.test-ldrjzaab/0.juju-log Unable to get SSH connection for instance test-ldrjzaab-0-n-5e6be518f048, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-ldrjzaab-0-n-5e6be518f048, key path: /home/runner-manager/.ssh/test-ldrjzaab-0-n-5e6be518f048.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-ldrjzaab-0-n-5e6be518f048
unit-test-ldrjzaab-0: 18:49:51 ERROR unit.test-ldrjzaab/0.juju-log Unable to get SSH connection for instance test-ldrjzaab-0-n-5e6be518f048, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-ldrjzaab-0-n-5e6be518f048, key path: /home/runner-manager/.ssh/test-ldrjzaab-0-n-5e6be518f048.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-ldrjzaab-0-n-5e6be518f048
unit-test-ldrjzaab-0: 18:49:51 ERROR unit.test-ldrjzaab/0.juju-log Failed to get SSH connection while removing test-ldrjzaab-0-n-5e6be518f048
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 311, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-ldrjzaab-0-n-5e6be518f048, key path: /home/runner-manager/.ssh/test-ldrjzaab-0-n-5e6be518f048.key
unit-test-ldrjzaab-0: 18:49:54 ERROR unit.test-ldrjzaab/0.juju-log Invalid pulled metrics. No runner_installed information for test-ldrjzaab-0-n-5e6be518f048.
unit-test-ldrjzaab-0: 18:49:54 ERROR unit.test-ldrjzaab/0.juju-log No metrics returned after deleting test-ldrjzaab-0-n-5e6be518f048
unit-test-ldrjzaab-0: 18:49:59 ERROR unit.test-ldrjzaab/0.juju-log Unable to get SSH connection for instance test-ldrjzaab-0-n-5e6be518f048, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-ldrjzaab-0-n-5e6be518f048, key path: /home/runner-manager/.ssh/test-ldrjzaab-0-n-5e6be518f048.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-ldrjzaab-0-n-5e6be518f048
unit-test-ldrjzaab-0: 18:50:04 ERROR unit.test-ldrjzaab/0.juju-log Failed to get SSH connection while removing test-ldrjzaab-0-n-5e6be518f048
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 311, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-ldrjzaab-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-ldrjzaab-0-n-5e6be518f048, key path: /home/runner-manager/.ssh/test-ldrjzaab-0-n-5e6be518f048.key
unit-test-ldrjzaab-0: 18:50:09 ERROR unit.test-ldrjzaab/0.juju-log Invalid pulled metrics. No runner_installed information for test-ldrjzaab-0-n-5e6be518f048.

18:57:39 INFO Forgetting model main...