INFO     juju.model:model.py:3211 Waiting for model:
  test-usex4xk0/0 [executing] active: 
INFO     juju.model:model.py:3211 Waiting for model:
  test-usex4xk0/0 [idle] active:
INFO     juju.model:model.py:3211 Waiting for model:
  test-usex4xk0/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:3211 Waiting for model:
  test-usex4xk0/0 [idle] active: 
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:368 Wait for condition not met, sleeping 10
INFO     juju.model:model.py:3211 Waiting for model:
  test-usex4xk0/0 [executing] active: 
INFO     juju.model:model.py:3211 Waiting for model:
  test-usex4xk0/0 [idle] active: 
INFO     pytest_operator.plugin:plugin.py:929 Model status:

Model               Controller  Cloud/Region         Version  SLA          Timestamp
test-reactive-ndi7  lxd         localhost/localhost  3.6.1    unsupported  13:46:19Z

App                          Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active      1  github-runner-image-builder  latest/edge    2  no       
mongodb                               active      1  mongodb                      6/edge       206  no       
test-usex4xk0                         active      1  github-runner                               0  no       

Unit                            Workload  Agent  Machine  Public address  Ports      Message
github-runner-image-builder/0*  active    idle   0        10.173.229.52              
mongodb/0*                      active    idle   2        10.173.229.228  27017/tcp  Primary
test-usex4xk0/0*                active    idle   1        10.173.229.11              

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.173.229.52   juju-35899b-0  ubuntu@22.04      Running
1        started  10.173.229.11   juju-35899b-1  ubuntu@22.04      Running
2        started  10.173.229.228  juju-35899b-2  ubuntu@22.04      Running

INFO     pytest_operator.plugin:plugin.py:935 Juju error logs:

machine-0: 12:54:27 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 12:54:27 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-0: 12:54:28 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 12:57:46 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 12:57:46 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-usex4xk0-0: 12:57:46 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 12:59:42 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 12:59:42 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mongodb-0: 12:59:42 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mongodb-0: 13:00:05 ERROR unit.mongodb/0.juju-log Unable to set params: ['vm.max_map_count']
unit-mongodb-0: 13:00:05 ERROR unit.mongodb/0.juju-log Error setting values on sysctl: Unable to set params: ['vm.max_map_count']
unit-mongodb-0: 13:00:45 ERROR unit.mongodb/0.juju-log _on_secret_remove: Secret secret:cti1hq0kocrd5at6ac50 seems to have no observers, could be removed
unit-test-usex4xk0-0: 13:03:16 ERROR unit.test-usex4xk0/0.juju-log SSH connection failure with test-usex4xk0-0-b14c78960172 during flushing
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 589, in _check_state_and_flush
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 328, in get_ssh_connection
    raise SSHError(f"No addresses found for OpenStack server {instance.server_name}")
github_runner_manager.errors.SSHError: No addresses found for OpenStack server test-usex4xk0-0-b14c78960172
unit-test-usex4xk0-0: 13:03:21 ERROR unit.test-usex4xk0/0.juju-log SSH connection failure with test-usex4xk0-0-b14c78960172 during flushing
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 589, in _check_state_and_flush
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 328, in get_ssh_connection
    raise SSHError(f"No addresses found for OpenStack server {instance.server_name}")
github_runner_manager.errors.SSHError: No addresses found for OpenStack server test-usex4xk0-0-b14c78960172
unit-test-usex4xk0-0: 13:03:31 ERROR unit.test-usex4xk0/0.juju-log SSH connection failure with test-usex4xk0-0-b14c78960172 during flushing
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 589, in _check_state_and_flush
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 328, in get_ssh_connection
    raise SSHError(f"No addresses found for OpenStack server {instance.server_name}")
github_runner_manager.errors.SSHError: No addresses found for OpenStack server test-usex4xk0-0-b14c78960172
unit-test-usex4xk0-0: 13:03:31 ERROR unit.test-usex4xk0/0.juju-log Retry limit of 3 exceed: No addresses found for OpenStack server test-usex4xk0-0-b14c78960172
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 589, in _check_state_and_flush
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 328, in get_ssh_connection
    raise SSHError(f"No addresses found for OpenStack server {instance.server_name}")
github_runner_manager.errors.SSHError: No addresses found for OpenStack server test-usex4xk0-0-b14c78960172
unit-test-usex4xk0-0: 13:03:38 ERROR unit.test-usex4xk0/0.juju-log Unable to get SSH connection for instance test-usex4xk0-0-b14c78960172, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 356, in get_ssh_connection
    raise SSHError(
github_runner_manager.errors.SSHError: No connectable SSH addresses found, server: test-usex4xk0-0-b14c78960172, addresses: ['10.145.193.50']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-usex4xk0-0-b14c78960172
unit-test-usex4xk0-0: 13:03:38 ERROR unit.test-usex4xk0/0.juju-log Failed to get SSH connection while removing test-usex4xk0-0-b14c78960172
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 440, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 356, in get_ssh_connection
    raise SSHError(
github_runner_manager.errors.SSHError: No connectable SSH addresses found, server: test-usex4xk0-0-b14c78960172, addresses: ['10.145.193.50']
unit-test-usex4xk0-0: 13:03:43 ERROR unit.test-usex4xk0/0.juju-log runner-installed.timestamp not found for runner test-usex4xk0-0-b14c78960172
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-usex4xk0-0-b14c78960172/runner-installed.timestamp'
unit-test-usex4xk0-0: 13:03:43 ERROR unit.test-usex4xk0/0.juju-log installed timestamp not found for runner test-usex4xk0-0-b14c78960172, will not extract any metrics.
unit-test-usex4xk0-0: 13:45:18 ERROR unit.test-usex4xk0/0.juju-log SSH connection failure with test-usex4xk0-0-48df92bcd8ff during flushing
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 589, in _check_state_and_flush
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 328, in get_ssh_connection
    raise SSHError(f"No addresses found for OpenStack server {instance.server_name}")
github_runner_manager.errors.SSHError: No addresses found for OpenStack server test-usex4xk0-0-48df92bcd8ff
unit-test-usex4xk0-0: 13:45:24 ERROR unit.test-usex4xk0/0.juju-log SSH connection failure with test-usex4xk0-0-48df92bcd8ff during flushing
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 589, in _check_state_and_flush
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 328, in get_ssh_connection
    raise SSHError(f"No addresses found for OpenStack server {instance.server_name}")
github_runner_manager.errors.SSHError: No addresses found for OpenStack server test-usex4xk0-0-48df92bcd8ff
unit-test-usex4xk0-0: 13:45:34 ERROR unit.test-usex4xk0/0.juju-log SSH connection failure with test-usex4xk0-0-48df92bcd8ff during flushing
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 589, in _check_state_and_flush
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 328, in get_ssh_connection
    raise SSHError(f"No addresses found for OpenStack server {instance.server_name}")
github_runner_manager.errors.SSHError: No addresses found for OpenStack server test-usex4xk0-0-48df92bcd8ff
unit-test-usex4xk0-0: 13:45:34 ERROR unit.test-usex4xk0/0.juju-log Retry limit of 3 exceed: No addresses found for OpenStack server test-usex4xk0-0-48df92bcd8ff
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 589, in _check_state_and_flush
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 328, in get_ssh_connection
    raise SSHError(f"No addresses found for OpenStack server {instance.server_name}")
github_runner_manager.errors.SSHError: No addresses found for OpenStack server test-usex4xk0-0-48df92bcd8ff
unit-test-usex4xk0-0: 13:45:38 ERROR unit.test-usex4xk0/0.juju-log runner-installed.timestamp not found for runner test-usex4xk0-0-ebdf67fa168b
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-usex4xk0-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-usex4xk0-0-ebdf67fa168b/runner-installed.timestamp'
unit-test-usex4xk0-0: 13:45:38 ERROR unit.test-usex4xk0/0.juju-log installed timestamp not found for runner test-usex4xk0-0-ebdf67fa168b, will not extract any metrics.

INFO     pytest_operator.plugin:plugin.py:1017 Forgetting model main...