18:41:18 INFO GitHub token rate limit: Rate(reset=2025-04-26 18:51:12+00:00, remaining=4617, limit=5000)
18:43:42 INFO Waiting for model:
  test-so3vno5f/0 [executing] maintenance: Reconciling runners
18:44:12 INFO Waiting for model:
  test-so3vno5f/0 [idle] active: 
18:44:19 INFO Wait for condition not met, sleeping 10
18:44:54 INFO Waiting for model:
  test-so3vno5f/0 [executing] active: 
18:45:25 INFO File content of /var/log/github-runner-metrics.log: {"timestamp": 1745692973.0, "event": "runner_installed", "flavor": "test-so3vno5f", "duration": 73.0}
{"timestamp": 1745693063.0, "event": "runner_start", "flavor": "test-so3vno5f", "workflow": "Workflow Dispatch Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "idle": 90.0, "queue_duration": 3.0}
{"timestamp": 1745693065.0, "event": "runner_stop", "flavor": "test-so3vno5f", "workflow": "Workflow Dispatch Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "status": "normal", "job_duration": 2.0, "job_conclusion": "success"}
{"timestamp": 1745693093.4027252, "event": "reconciliation", "flavor": "test-so3vno5f", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 20.687241792678833}
{"timestamp": 1745693107.6172152, "event": "reconciliation", "flavor": "test-so3vno5f", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 12.975140571594238}
18:45:27 INFO Model status:

Model                            Controller           Cloud/Region         Version  SLA          Timestamp
test-charm-metrics-success-zc38  github-pr-223ed-lxd  localhost/localhost  3.6.5    unsupported  18:45:27Z

App                                   Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder-so3vno5f           active      1  github-runner-image-builder  latest/edge   68  no       
test-so3vno5f                                  active      1  github-runner                               0  no       

Unit                                     Workload  Agent  Machine  Public address  Ports  Message
github-runner-image-builder-so3vno5f/0*  active    idle   0        10.127.83.58           
test-so3vno5f/0*                         active    idle   1        10.127.83.175          

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.127.83.58   juju-fdebd7-0  ubuntu@22.04      Running
1        started  10.127.83.175  juju-fdebd7-1  ubuntu@22.04      Running

18:45:27 INFO Juju error logs:

machine-0: 18:25:05 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 18:25:05 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-so3vno5f-0: 18:25:05 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 18:25:12 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 18:25:12 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-so3vno5f-0: 18:25:12 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-github-runner-image-builder-so3vno5f-0: 18:25:41 ERROR unit.github-runner-image-builder-so3vno5f/0.juju-log Pipx command failed, code: 1, out: None, err: None
unit-test-so3vno5f-0: 18:40:41 ERROR unit.test-so3vno5f/0.juju-log Unable to get SSH connection for instance test-so3vno5f-0-n-0dbd8ef5ebde, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-so3vno5f-0-n-0dbd8ef5ebde, key path: /home/runner-manager/.ssh/test-so3vno5f-0-n-0dbd8ef5ebde.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-so3vno5f-0-n-0dbd8ef5ebde
unit-test-so3vno5f-0: 18:40:45 ERROR unit.test-so3vno5f/0.juju-log Unable to get SSH connection for instance test-so3vno5f-0-n-0dbd8ef5ebde, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-so3vno5f-0-n-0dbd8ef5ebde, key path: /home/runner-manager/.ssh/test-so3vno5f-0-n-0dbd8ef5ebde.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-so3vno5f-0-n-0dbd8ef5ebde
unit-test-so3vno5f-0: 18:40:49 ERROR unit.test-so3vno5f/0.juju-log Unable to get SSH connection for instance test-so3vno5f-0-n-0dbd8ef5ebde, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-so3vno5f-0-n-0dbd8ef5ebde, key path: /home/runner-manager/.ssh/test-so3vno5f-0-n-0dbd8ef5ebde.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-so3vno5f-0-n-0dbd8ef5ebde
unit-test-so3vno5f-0: 18:40:49 ERROR unit.test-so3vno5f/0.juju-log Failed to get SSH connection while removing test-so3vno5f-0-n-0dbd8ef5ebde
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 319, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-so3vno5f-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-so3vno5f-0-n-0dbd8ef5ebde, key path: /home/runner-manager/.ssh/test-so3vno5f-0-n-0dbd8ef5ebde.key
unit-test-so3vno5f-0: 18:40:51 ERROR unit.test-so3vno5f/0.juju-log Invalid pulled metrics. No runner_installed information for test-so3vno5f-0-n-0dbd8ef5ebde.
unit-test-so3vno5f-0: 18:40:51 ERROR unit.test-so3vno5f/0.juju-log No metrics returned after deleting test-so3vno5f-0-n-0dbd8ef5ebde

18:45:27 INFO Forgetting model main...