19:13:15 INFO GitHub token rate limit: Rate(reset=2025-04-13 20:11:27+00:00, remaining=4895, limit=5000)
19:15:05 INFO Waiting for model:
  test-lqi97o91/0 [executing] maintenance: Reconciling runners
19:15:35 INFO Waiting for model:
  test-lqi97o91/0 [idle] active: 
19:15:41 INFO Wait for condition not met, sleeping 10
19:16:15 INFO Waiting for model:
  test-lqi97o91/0 [executing] active: 
19:16:43 INFO File content of /var/log/github-runner-metrics.log: {"timestamp": 1744571662.0, "event": "runner_installed", "flavor": "test-lqi97o91", "duration": 48.0}
{"timestamp": 1744571745.0, "event": "runner_start", "flavor": "test-lqi97o91", "workflow": "Workflow Dispatch Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "idle": 83.0, "queue_duration": 3.0}
{"timestamp": 1744571747.0, "event": "runner_stop", "flavor": "test-lqi97o91", "workflow": "Workflow Dispatch Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "status": "normal", "job_duration": 2.0, "job_conclusion": "success"}
{"timestamp": 1744571774.35624, "event": "reconciliation", "flavor": "test-lqi97o91", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 18.996438026428223}
{"timestamp": 1744571787.4712877, "event": "reconciliation", "flavor": "test-lqi97o91", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 11.941018342971802}
19:16:45 INFO Model status:

Model                            Controller           Cloud/Region         Version  SLA          Timestamp
test-charm-metrics-success-41ho  github-pr-5e3eb-lxd  localhost/localhost  3.6.4    unsupported  19:16:45Z

App                                   Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder-lqi97o91           active      1  github-runner-image-builder  latest/edge   68  no       
test-lqi97o91                                  active      1  github-runner                               0  no       

Unit                                     Workload  Agent  Machine  Public address  Ports  Message
github-runner-image-builder-lqi97o91/0*  active    idle   0        10.241.14.176          
test-lqi97o91/0*                         active    idle   1        10.241.14.58           

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.241.14.176  juju-a15023-0  ubuntu@22.04      Running
1        started  10.241.14.58   juju-a15023-1  ubuntu@22.04      Running

19:16:45 INFO Juju error logs:

machine-0: 18:52:48 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 18:52:48 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-lqi97o91-0: 18:52:48 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-github-runner-image-builder-lqi97o91-0: 18:53:26 ERROR unit.github-runner-image-builder-lqi97o91/0.juju-log Pipx command failed, code: 1, out: None, err: None
machine-1: 18:56:42 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 18:56:42 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-lqi97o91-0: 18:56:42 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-test-lqi97o91-0: 19:12:31 ERROR unit.test-lqi97o91/0.juju-log Unable to get SSH connection for instance test-lqi97o91-0-n-88b13420851e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 111, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 308, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-lqi97o91-0-n-88b13420851e, key path: /home/runner-manager/.ssh/test-lqi97o91-0-n-88b13420851e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-lqi97o91-0-n-88b13420851e
unit-test-lqi97o91-0: 19:12:35 ERROR unit.test-lqi97o91/0.juju-log Unable to get SSH connection for instance test-lqi97o91-0-n-88b13420851e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 111, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 308, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-lqi97o91-0-n-88b13420851e, key path: /home/runner-manager/.ssh/test-lqi97o91-0-n-88b13420851e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-lqi97o91-0-n-88b13420851e
unit-test-lqi97o91-0: 19:12:39 ERROR unit.test-lqi97o91/0.juju-log Unable to get SSH connection for instance test-lqi97o91-0-n-88b13420851e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 111, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 308, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-lqi97o91-0-n-88b13420851e, key path: /home/runner-manager/.ssh/test-lqi97o91-0-n-88b13420851e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-lqi97o91-0-n-88b13420851e
unit-test-lqi97o91-0: 19:12:39 ERROR unit.test-lqi97o91/0.juju-log Failed to get SSH connection while removing test-lqi97o91-0-n-88b13420851e
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 316, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 111, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 308, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-lqi97o91-0-n-88b13420851e, key path: /home/runner-manager/.ssh/test-lqi97o91-0-n-88b13420851e.key
unit-test-lqi97o91-0: 19:12:42 ERROR unit.test-lqi97o91/0.juju-log Invalid pulled metrics. No runner_installed information for test-lqi97o91-0-n-88b13420851e.
unit-test-lqi97o91-0: 19:12:42 ERROR unit.test-lqi97o91/0.juju-log No metrics returned after deleting test-lqi97o91-0-n-88b13420851e
unit-test-lqi97o91-0: 19:12:47 ERROR unit.test-lqi97o91/0.juju-log Unable to get SSH connection for instance test-lqi97o91-0-n-88b13420851e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 111, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 308, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-lqi97o91-0-n-88b13420851e, key path: /home/runner-manager/.ssh/test-lqi97o91-0-n-88b13420851e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-lqi97o91-0-n-88b13420851e
unit-test-lqi97o91-0: 19:12:50 ERROR unit.test-lqi97o91/0.juju-log Unable to get SSH connection for instance test-lqi97o91-0-n-88b13420851e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 111, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 308, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-lqi97o91-0-n-88b13420851e, key path: /home/runner-manager/.ssh/test-lqi97o91-0-n-88b13420851e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-lqi97o91-0-n-88b13420851e
unit-test-lqi97o91-0: 19:12:52 ERROR unit.test-lqi97o91/0.juju-log Failed to get SSH connection while removing test-lqi97o91-0-n-88b13420851e
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 316, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 111, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 308, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-lqi97o91-0-n-88b13420851e, key path: /home/runner-manager/.ssh/test-lqi97o91-0-n-88b13420851e.key
unit-test-lqi97o91-0: 19:12:54 ERROR unit.test-lqi97o91/0.juju-log Invalid pulled metrics. No runner_installed information for test-lqi97o91-0-n-88b13420851e.
unit-test-lqi97o91-0: 19:12:57 ERROR unit.test-lqi97o91/0.juju-log Unable to get SSH connection for instance test-lqi97o91-0-n-88b13420851e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 111, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 308, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-lqi97o91-0-n-88b13420851e, key path: /home/runner-manager/.ssh/test-lqi97o91-0-n-88b13420851e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-lqi97o91-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-lqi97o91-0-n-88b13420851e

19:16:45 INFO Forgetting model main...