INFO     pytest_operator.plugin:plugin.py:929 Model status:

Model                            Controller  Cloud/Region         Version  SLA          Timestamp
test-charm-metrics-failure-2ced  lxd         localhost/localhost  3.6.1    unsupported  07:18:48Z

App                          Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active      1  github-runner-image-builder  latest/edge    2  no       
test-naml0mas                         active      1  github-runner                               0  yes      

Unit                            Workload  Agent  Machine  Public address  Ports     Message
github-runner-image-builder/0*  active    idle   0        10.100.140.242            
test-naml0mas/0*                active    idle   1        10.100.140.88   8080/tcp  

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.100.140.242  juju-0da0de-0  ubuntu@22.04      Running
1        started  10.100.140.88   juju-0da0de-1  ubuntu@22.04      Running

INFO     pytest_operator.plugin:plugin.py:935 Juju error logs:

machine-0: 06:57:09 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 06:57:09 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-0: 06:57:09 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 07:00:22 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 07:00:22 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-naml0mas-0: 07:00:22 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-test-naml0mas-0: 07:00:37 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:00:38 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:00:41 CRITICAL unit.test-naml0mas/0.juju-log image:0: test mode is enabled
unit-test-naml0mas-0: 07:00:42 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:00:43 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:00:44 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:00:46 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:00:47 CRITICAL unit.test-naml0mas/0.juju-log image:0: test mode is enabled
unit-test-naml0mas-0: 07:00:48 CRITICAL unit.test-naml0mas/0.juju-log image:0: test mode is enabled
unit-test-naml0mas-0: 07:01:34 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:01:36 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:01:58 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:02:25 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:02:38 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:03:17 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:03:18 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:08:34 ERROR unit.test-naml0mas/0.juju-log Timeout creating openstack server test-naml0mas-0-93e982fe0c6f
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/openstack/cloud/_compute.py", line 1021, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/openstack/cloud/_compute.py", line 1142, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/openstack/utils.py", line 73, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.
unit-test-naml0mas-0: 07:08:38 ERROR unit.test-naml0mas/0.juju-log Failed to spawn a runner.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/openstack/cloud/_compute.py", line 1021, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/openstack/cloud/_compute.py", line 1142, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/openstack/utils.py", line 73, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 209, in create_runner
    instance = self._openstack_cloud.launch_instance(
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 246, in launch_instance
    raise OpenStackError(f"Timeout creating openstack server {full_name}") from err
github_runner_manager.errors.OpenStackError: Timeout creating openstack server test-naml0mas-0-93e982fe0c6f

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 276, in _spawn_runners
    return (RunnerManager._create_runner(create_runner_args_sequence[0]),)
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 404, in _create_runner
    return args.cloud_runner_manager.create_runner(registration_token=args.registration_token)
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 217, in create_runner
    raise RunnerCreateError(f"Failed to create {instance_name} openstack runner") from err
github_runner_manager.errors.RunnerCreateError: Failed to create test-naml0mas-0-93e982fe0c6f openstack runner
unit-test-naml0mas-0: 07:08:44 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled
unit-test-naml0mas-0: 07:13:09 CRITICAL unit.test-naml0mas/0.juju-log image:0: test mode is enabled
unit-test-naml0mas-0: 07:13:16 ERROR unit.test-naml0mas/0.juju-log image:0: runner-installed.timestamp not found for runner test-naml0mas-0-93e982fe0c6f
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-naml0mas-0-93e982fe0c6f/runner-installed.timestamp'
unit-test-naml0mas-0: 07:13:16 ERROR unit.test-naml0mas/0.juju-log image:0: installed timestamp not found for runner test-naml0mas-0-93e982fe0c6f, will not extract any metrics.
unit-test-naml0mas-0: 07:13:33 ERROR unit.test-naml0mas/0.juju-log image:0: pre-job-metrics.json not found for runner test-naml0mas-0-7219dac26760
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-naml0mas-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-naml0mas-0-7219dac26760/pre-job-metrics.json'
unit-test-naml0mas-0: 07:13:33 ERROR unit.test-naml0mas/0.juju-log image:0: Pre-job metrics for runner test-naml0mas-0-7219dac26760 not found, stop extracting post-jobs metrics.
unit-test-naml0mas-0: 07:18:39 CRITICAL unit.test-naml0mas/0.juju-log test mode is enabled

INFO     pytest_operator.plugin:plugin.py:1017 Forgetting model main...