06:55:36 INFO Model status:

Model                            Controller           Cloud/Region         Version  SLA          Timestamp
test-charm-metrics-failure-h3r5  github-pr-c3380-lxd  localhost/localhost  3.6.6    unsupported  06:55:36Z

App                                   Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder-vly4avzd           active      1  github-runner-image-builder  latest/edge   84  no       
test-vly4avzd                                  active      1  github-runner                               0  yes      

Unit                                     Workload  Agent  Machine  Public address  Ports     Message
github-runner-image-builder-vly4avzd/0*  active    idle   0        10.18.174.168             
test-vly4avzd/0*                         active    idle   1        10.18.174.74    8080/tcp  

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.18.174.168  juju-59e703-0  ubuntu@22.04      Running
1        started  10.18.174.74   juju-59e703-1  ubuntu@22.04      Running

06:55:36 INFO Juju error logs:

machine-0: 06:25:59 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 06:25:59 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-vly4avzd-0: 06:25:59 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 06:26:04 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 06:26:04 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-vly4avzd-0: 06:26:04 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-github-runner-image-builder-vly4avzd-0: 06:26:42 ERROR unit.github-runner-image-builder-vly4avzd/0.juju-log Pipx command failed, code: 1, out: None, err: None
unit-test-vly4avzd-0: 06:54:40 ERROR unit.test-vly4avzd/0.juju-log Timeout creating openstack server test-vly4avzd-0-n-7a1698fa55c5
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 245, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/decorator.py", line 235, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/openstack/cloud/_utils.py", line 233, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/openstack/cloud/_compute.py", line 1104, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/openstack/cloud/_compute.py", line 1243, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/openstack/utils.py", line 88, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.
unit-test-vly4avzd-0: 06:54:47 ERROR unit.test-vly4avzd/0.juju-log Failed to spawn a runner.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 245, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/decorator.py", line 235, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/openstack/cloud/_utils.py", line 233, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/openstack/cloud/_compute.py", line 1104, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/openstack/cloud/_compute.py", line 1243, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/openstack/utils.py", line 88, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 140, in create_runner
    instance = self._openstack_cloud.launch_instance(
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 144, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 265, in launch_instance
    raise OpenStackError(f"Timeout creating openstack server {instance_id}") from err
github_runner_manager.errors.OpenStackError: Timeout creating openstack server test-vly4avzd-0-n-7a1698fa55c5

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 391, in _spawn_runners
    return (RunnerManager._create_runner(create_runner_args_sequence[0]),)
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 521, in _create_runner
    args.cloud_runner_manager.create_runner(
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 147, in create_runner
    raise RunnerCreateError(
github_runner_manager.errors.RunnerCreateError: Failed to create RunnerIdentity(instance_id=InstanceID('test-vly4avzd-0-n-7a1698fa55c5'), metadata=RunnerMetadata(platform_name='github', runner_id='8175', url=None)) openstack runner
unit-test-vly4avzd-0: 06:55:03 ERROR unit.test-vly4avzd/0.juju-log Failed to get SSH connection while removing test-vly4avzd-0-n-7a1698fa55c5
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 216, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 144, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-vly4avzd-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 340, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-vly4avzd-0-n-7a1698fa55c5, key path: /home/runner-manager/.ssh/test-vly4avzd-0-n-7a1698fa55c5.key
unit-test-vly4avzd-0: 06:55:04 ERROR unit.test-vly4avzd/0.juju-log Invalid pulled metrics. No runner_installed information for test-vly4avzd-0-n-7a1698fa55c5.
unit-test-vly4avzd-0: 06:55:04 ERROR unit.test-vly4avzd/0.juju-log No metrics returned after deleting test-vly4avzd-0-n-7a1698fa55c5

06:55:36 INFO Forgetting model main...