06:25:01 INFO Creating 1 runners
06:25:01 INFO Creating openstack server with test-y1n89ouy-0-n-d00ccd170576
06:25:34 WARNING NoValidConnectionsError. Unable to SSH into test-y1n89ouy-0-n-d00ccd170576 with address 10.145.193.203. Error: [Errno None] Unable to connect to port 22 on 10.145.193.203
06:25:34 WARNING Retrying error in 60 seconds: Failed to SSH to test-y1n89ouy-0-n-d00ccd170576 during creation possible due to setup not completed
06:26:34 INFO Connected (version 2.0, client OpenSSH_9.6p1)
06:26:35 INFO Authentication (publickey) successful!
06:26:36 INFO Runner startup process found to be healthy on test-y1n89ouy-0-n-d00ccd170576
06:26:36 INFO Connected (version 2.0, client OpenSSH_9.6p1)
06:26:36 INFO Authentication (publickey) successful!
06:26:36 INFO Runner test-y1n89ouy-0-n-d00ccd170576 found to be healthy
06:26:36 INFO Runner test-y1n89ouy-0-n-d00ccd170576 created successfully
06:26:36 INFO Getting runners...
06:26:38 INFO Getting all openstack servers managed by the charm
06:26:42 INFO Connected (version 2.0, client OpenSSH_9.6p1)
06:26:42 INFO Authentication (publickey) successful!
06:26:42 INFO Found following runners: {'test-y1n89ouy-0-n-d00ccd170576'}
06:26:42 INFO Getting runners...
06:26:43 INFO Getting all openstack servers managed by the charm
06:26:48 INFO Connected (version 2.0, client OpenSSH_9.6p1)
06:26:48 INFO Authentication (publickey) successful!
06:26:49 INFO Found following runners: {'test-y1n89ouy-0-n-d00ccd170576'}
06:26:49 INFO Getting runners...
06:26:50 INFO Getting all openstack servers managed by the charm
06:26:58 INFO Connected (version 2.0, client OpenSSH_9.6p1)
06:26:58 INFO Authentication (publickey) successful!
06:26:59 INFO Found following runners: {'test-y1n89ouy-0-n-d00ccd170576'}
06:26:59 INFO Getting all openstack servers managed by the charm
06:27:02 INFO Connected (version 2.0, client OpenSSH_9.6p1)
06:27:02 INFO Authentication (publickey) successful!
06:27:02 INFO Getting runners...
06:27:03 INFO Getting all openstack servers managed by the charm
06:27:06 INFO Connected (version 2.0, client OpenSSH_9.6p1)
06:27:06 INFO Authentication (publickey) successful!
06:27:06 INFO Found following runners: {'test-y1n89ouy-0-n-d00ccd170576'}
06:27:07 INFO Offline github runners to delete: []:
06:27:08 INFO Getting all openstack servers managed by the charm
06:27:10 INFO Connected (version 2.0, client OpenSSH_9.6p1)
06:27:10 INFO Authentication (publickey) successful!
06:27:13 INFO Cleaning up SSH key files
06:27:13 INFO Found 1 key files, clean up 0 key files
06:27:13 INFO Cleaning up openstack keypairs
06:27:13 INFO Getting runners...
06:27:14 INFO Getting all openstack servers managed by the charm
06:27:17 INFO Connected (version 2.0, client OpenSSH_9.6p1)
06:27:17 INFO Authentication (publickey) successful!
06:27:18 INFO Found following runners: {'test-y1n89ouy-0-n-d00ccd170576'}
06:27:18 INFO Flushing idle runners...
06:27:18 INFO Getting all openstack servers managed by the charm
06:27:21 INFO Connected (version 2.0, client OpenSSH_9.6p1)
06:27:21 INFO Authentication (publickey) successful!
06:27:21 INFO Attempting to kill runner process on test-y1n89ouy-0-n-d00ccd170576 if not busy
06:27:21 INFO Running kill process command: ! pgrep -x Runner.Worker && pgrep -x Runner.Listener && kill $(pgrep -x Runner.Listener)
06:27:21 INFO Kill process command output, ok: True code 0, out: 1797
, err: 
06:27:21 INFO Getting all openstack servers managed by the charm
06:27:23 INFO Connected (version 2.0, client OpenSSH_9.6p1)
06:27:23 INFO Authentication (publickey) successful!
06:27:24 INFO Connected (version 2.0, client OpenSSH_9.6p1)
06:27:24 INFO Authentication (publickey) successful!
06:27:24 INFO [chan 2] Opened sftp connection (server version 3)
06:27:24 WARNING Unable to get file size of /home/ubuntu/metrics-exchange/pre-job-metrics.json on instance 10.145.193.203, exit code: 1, stdout: , stderr: stat: cannot statx '/home/ubuntu/metrics-exchange/pre-job-metrics.json': No such file or directory

06:27:24 WARNING Failed to pull metrics for test-y1n89ouy-0-n-d00ccd170576: Unable to get file size of /home/ubuntu/metrics-exchange/pre-job-metrics.json . Will not be able to issue all metrics
06:27:24 INFO Running runner removal script for test-y1n89ouy-0-n-d00ccd170576
06:27:26 INFO Deleting openstack server with test-y1n89ouy-0-n-d00ccd170576
06:27:29 INFO Cleaning up SSH key files
06:27:29 INFO Found 0 key files, clean up 0 key files
06:27:29 INFO Cleaning up openstack keypairs
06:27:29 INFO Getting runners...
06:27:30 INFO Getting all openstack servers managed by the charm
06:27:32 ERROR Unable to get SSH connection for instance test-y1n89ouy-0-n-d00ccd170576, marking as unhealthy.
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 106, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 297, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-y1n89ouy-0-n-d00ccd170576, key path: /home/ubuntu/.ssh/test-y1n89ouy-0-n-d00ccd170576.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-y1n89ouy-0-n-d00ccd170576
06:27:32 INFO Found following runners: {'test-y1n89ouy-0-n-d00ccd170576'}
06:27:32 WARNING Found runner instance on cloud but not registered on GitHub: {'test-y1n89ouy-0-n-d00ccd170576'}
06:27:32 INFO Getting runners...
06:27:33 INFO Getting all openstack servers managed by the charm
06:27:35 ERROR Unable to get SSH connection for instance test-y1n89ouy-0-n-d00ccd170576, marking as unhealthy.
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 106, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 297, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-y1n89ouy-0-n-d00ccd170576, key path: /home/ubuntu/.ssh/test-y1n89ouy-0-n-d00ccd170576.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-y1n89ouy-0-n-d00ccd170576
06:27:35 INFO Found following runners: {'test-y1n89ouy-0-n-d00ccd170576'}
06:27:35 WARNING Found runner instance on cloud but not registered on GitHub: {'test-y1n89ouy-0-n-d00ccd170576'}
06:27:35 INFO Wait for condition not met, sleeping 60
06:28:35 INFO Getting runners...
06:28:36 INFO Getting all openstack servers managed by the charm
06:28:38 INFO Found following runners: set()