INFO     root:conftest.py:589 GitHub token rate limit: Rate(reset=2024-12-21 19:29:42+00:00, remaining=4890, limit=5000)
INFO     root:charm_metrics.py:127 Loop device None not found
INFO     juju.model:__init__.py:3254 Waiting for model:
  test-u1oreikr/0 [executing] active: 
INFO     juju.model:__init__.py:3254 Waiting for model:
  test-u1oreikr/0 [idle] active: 
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 60
INFO     juju.model:__init__.py:3254 Waiting for model:
  test-u1oreikr/0 [executing] active: 
INFO     juju.model:__init__.py:3254 Waiting for model:
  test-u1oreikr/0 [idle] active: 
INFO     root:common.py:609 File content of /var/log/github-runner-metrics.log: {"timestamp": 1734807622.0, "event": "runner_installed", "flavor": "test-u1oreikr", "duration": 78.3496253490448}
{"timestamp": 1734807698.0, "event": "runner_start", "flavor": "test-u1oreikr", "workflow": "Workflow Dispatch Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "idle": 76.0, "queue_duration": 6.0}
{"timestamp": 1734807706.0, "event": "runner_stop", "flavor": "test-u1oreikr", "workflow": "Workflow Dispatch Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "status": "normal", "job_duration": 8.0, "job_conclusion": "success"}
{"timestamp": 1734807797.0144572, "event": "reconciliation", "flavor": "test-u1oreikr", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 33.41977620124817}
{"timestamp": 1734807818.148359, "event": "reconciliation", "flavor": "test-u1oreikr", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 20.14067578315735}
INFO     pytest_operator.plugin:plugin.py:929 Model status:

Model                            Controller  Cloud/Region         Version  SLA          Timestamp
test-charm-metrics-success-zdn5  lxd         localhost/localhost  3.6.1    unsupported  19:03:57Z

App                          Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active      1  github-runner-image-builder  latest/edge    2  no       
test-u1oreikr                         active      1  github-runner                               0  no       

Unit                            Workload  Agent  Machine  Public address  Ports  Message
github-runner-image-builder/0*  active    idle   0        10.26.124.76           
test-u1oreikr/0*                active    idle   1        10.26.124.194          

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.26.124.76   juju-9f79f8-0  ubuntu@22.04      Running
1        started  10.26.124.194  juju-9f79f8-1  ubuntu@22.04      Running

INFO     pytest_operator.plugin:plugin.py:935 Juju error logs:

machine-0: 18:49:09 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 18:49:09 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-0: 18:49:09 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 18:52:31 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 18:52:31 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-u1oreikr-0: 18:52:31 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-test-u1oreikr-0: 18:52:47 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:52:48 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:52:51 CRITICAL unit.test-u1oreikr/0.juju-log image:0: test mode is enabled
unit-test-u1oreikr-0: 18:52:52 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:52:53 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:52:54 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:52:56 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:52:57 CRITICAL unit.test-u1oreikr/0.juju-log image:0: test mode is enabled
unit-test-u1oreikr-0: 18:52:58 CRITICAL unit.test-u1oreikr/0.juju-log image:0: test mode is enabled
unit-test-u1oreikr-0: 18:53:39 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:53:41 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:56:58 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:57:16 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:57:33 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:57:34 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:58:06 ERROR unit.test-u1oreikr/0.juju-log pre-job-metrics.json not found for runner test-u1oreikr-0-8a46d308e04a
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-u1oreikr-0-8a46d308e04a/pre-job-metrics.json'
unit-test-u1oreikr-0: 18:58:06 ERROR unit.test-u1oreikr/0.juju-log Pre-job metrics for runner test-u1oreikr-0-8a46d308e04a not found, stop extracting post-jobs metrics.
unit-test-u1oreikr-0: 18:58:11 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:58:51 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 18:58:53 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 19:00:54 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 19:02:42 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 19:02:43 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 19:03:02 ERROR unit.test-u1oreikr/0.juju-log Unable to get SSH connection for instance test-u1oreikr-0-7125fb4a0a75, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u1oreikr-0-7125fb4a0a75, key path: /home/runner-manager/.ssh/test-u1oreikr-0-7125fb4a0a75.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-u1oreikr-0-7125fb4a0a75
unit-test-u1oreikr-0: 19:03:07 ERROR unit.test-u1oreikr/0.juju-log Unable to get SSH connection for instance test-u1oreikr-0-7125fb4a0a75, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u1oreikr-0-7125fb4a0a75, key path: /home/runner-manager/.ssh/test-u1oreikr-0-7125fb4a0a75.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-u1oreikr-0-7125fb4a0a75
unit-test-u1oreikr-0: 19:03:10 ERROR unit.test-u1oreikr/0.juju-log Failed to get SSH connection while removing test-u1oreikr-0-7125fb4a0a75
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 441, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u1oreikr-0-7125fb4a0a75, key path: /home/runner-manager/.ssh/test-u1oreikr-0-7125fb4a0a75.key
unit-test-u1oreikr-0: 19:03:16 ERROR unit.test-u1oreikr/0.juju-log Unable to get SSH connection for instance test-u1oreikr-0-7125fb4a0a75, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u1oreikr-0-7125fb4a0a75, key path: /home/runner-manager/.ssh/test-u1oreikr-0-7125fb4a0a75.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-u1oreikr-0-7125fb4a0a75
unit-test-u1oreikr-0: 19:03:17 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled
unit-test-u1oreikr-0: 19:03:22 ERROR unit.test-u1oreikr/0.juju-log Unable to get SSH connection for instance test-u1oreikr-0-7125fb4a0a75, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u1oreikr-0-7125fb4a0a75, key path: /home/runner-manager/.ssh/test-u1oreikr-0-7125fb4a0a75.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-u1oreikr-0-7125fb4a0a75
unit-test-u1oreikr-0: 19:03:22 ERROR unit.test-u1oreikr/0.juju-log Failed to get SSH connection while removing test-u1oreikr-0-7125fb4a0a75
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 441, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u1oreikr-0-7125fb4a0a75, key path: /home/runner-manager/.ssh/test-u1oreikr-0-7125fb4a0a75.key
unit-test-u1oreikr-0: 19:03:30 ERROR unit.test-u1oreikr/0.juju-log Unable to get SSH connection for instance test-u1oreikr-0-7125fb4a0a75, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-u1oreikr-0-7125fb4a0a75, key path: /home/runner-manager/.ssh/test-u1oreikr-0-7125fb4a0a75.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-u1oreikr-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-u1oreikr-0-7125fb4a0a75
unit-test-u1oreikr-0: 19:03:38 CRITICAL unit.test-u1oreikr/0.juju-log test mode is enabled

INFO     pytest_operator.plugin:plugin.py:1017 Forgetting model main...