INFO     pytest_operator.plugin:plugin.py:745 Adding model lxd:test-charm-upgrade-9wyp on cloud localhost
WARNING  juju.client.connection:connection.py:893 unexpected facade AgentLifeFlag received from the controller
WARNING  juju.client.connection:connection.py:909 unknown common facade version for AgentLifeFlag,
versions known to client : [2, 3]
versions known to controller : [1]
WARNING  juju.client.connection:connection.py:893 unexpected facade SecretsDrain received from the controller
INFO     juju.model:model.py:1988 Deploying ch:amd64/github-runner-image-builder-2
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder (not enough units yet - 0/1)
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [idle] active:
INFO     juju.model:model.py:1988 Deploying local:jammy/github-runner-0
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Update image for runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [idle] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-dw9uw2ut/0 [idle] active:
INFO     pytest_operator.plugin:plugin.py:929 Model status:

Model                    Controller  Cloud/Region         Version  SLA          Timestamp
test-charm-upgrade-9wyp  lxd         localhost/localhost  3.1.10   unsupported  06:51:59Z

App                          Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active      1  github-runner-image-builder  latest/edge    2  no       
test-dw9uw2ut                         active      1  github-runner                               1  no       

Unit                            Workload  Agent  Machine  Public address  Ports  Message
github-runner-image-builder/0*  active    idle   0        10.106.84.64           
test-dw9uw2ut/0*                active    idle   1        10.106.84.188          

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.106.84.64   juju-fe0313-0  ubuntu@22.04      Running
1        started  10.106.84.188  juju-fe0313-1  ubuntu@22.04      Running

INFO     pytest_operator.plugin:plugin.py:935 Juju error logs:

machine-0: 06:24:43 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 06:24:43 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-0: 06:24:43 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-0: 06:24:43 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 06:27:34 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 06:27:34 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 06:27:34 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-test-dw9uw2ut-0: 06:27:34 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-test-dw9uw2ut-0: 06:33:26 ERROR unit.test-dw9uw2ut/0.juju-log image:0: Timeout creating openstack server test-dw9uw2ut-0-dab7a1aa3238
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1021, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1142, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/utils.py", line 73, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.
unit-test-dw9uw2ut-0: 06:33:27 ERROR unit.test-dw9uw2ut/0.juju-log image:0: Failed to spawn a runner.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1021, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1142, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/utils.py", line 73, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 204, in create_runner
    instance = self._openstack_cloud.launch_instance(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 246, in launch_instance
    raise OpenStackError(f"Timeout creating openstack server {full_name}") from err
github_runner_manager.errors.OpenStackError: Timeout creating openstack server test-dw9uw2ut-0-dab7a1aa3238

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 276, in _spawn_runners
    return (RunnerManager._create_runner(create_runner_args_sequence[0]),)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 404, in _create_runner
    return args.cloud_runner_manager.create_runner(registration_token=args.registration_token)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 212, in create_runner
    raise RunnerCreateError(f"Failed to create {instance_name} openstack runner") from err
github_runner_manager.errors.RunnerCreateError: Failed to create test-dw9uw2ut-0-dab7a1aa3238 openstack runner
unit-test-dw9uw2ut-0: 06:34:10 ERROR unit.test-dw9uw2ut/0.juju-log runner-installed.timestamp not found for runner test-dw9uw2ut-0-dab7a1aa3238
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-dw9uw2ut-0-dab7a1aa3238/runner-installed.timestamp'
unit-test-dw9uw2ut-0: 06:34:10 ERROR unit.test-dw9uw2ut/0.juju-log installed timestamp not found for runner test-dw9uw2ut-0-dab7a1aa3238, will not extract any metrics.
unit-test-dw9uw2ut-0: 06:39:20 ERROR unit.test-dw9uw2ut/0.juju-log Timeout creating openstack server test-dw9uw2ut-0-8d8f797dabfa
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1021, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1142, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/utils.py", line 73, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.
unit-test-dw9uw2ut-0: 06:39:22 ERROR unit.test-dw9uw2ut/0.juju-log Failed to spawn a runner.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1021, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1142, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/utils.py", line 73, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 204, in create_runner
    instance = self._openstack_cloud.launch_instance(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 246, in launch_instance
    raise OpenStackError(f"Timeout creating openstack server {full_name}") from err
github_runner_manager.errors.OpenStackError: Timeout creating openstack server test-dw9uw2ut-0-8d8f797dabfa

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 276, in _spawn_runners
    return (RunnerManager._create_runner(create_runner_args_sequence[0]),)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 404, in _create_runner
    return args.cloud_runner_manager.create_runner(registration_token=args.registration_token)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 212, in create_runner
    raise RunnerCreateError(f"Failed to create {instance_name} openstack runner") from err
github_runner_manager.errors.RunnerCreateError: Failed to create test-dw9uw2ut-0-8d8f797dabfa openstack runner
unit-test-dw9uw2ut-0: 06:39:46 ERROR unit.test-dw9uw2ut/0.juju-log image:0: runner-installed.timestamp not found for runner test-dw9uw2ut-0-8d8f797dabfa
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-dw9uw2ut-0-8d8f797dabfa/runner-installed.timestamp'
unit-test-dw9uw2ut-0: 06:39:46 ERROR unit.test-dw9uw2ut/0.juju-log image:0: installed timestamp not found for runner test-dw9uw2ut-0-8d8f797dabfa, will not extract any metrics.
unit-test-dw9uw2ut-0: 06:45:03 ERROR unit.test-dw9uw2ut/0.juju-log image:0: Timeout creating openstack server test-dw9uw2ut-0-1cc2b8888ea8
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1021, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1142, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/utils.py", line 73, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.
unit-test-dw9uw2ut-0: 06:45:05 ERROR unit.test-dw9uw2ut/0.juju-log image:0: Failed to spawn a runner.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1021, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1142, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/utils.py", line 73, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 204, in create_runner
    instance = self._openstack_cloud.launch_instance(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 246, in launch_instance
    raise OpenStackError(f"Timeout creating openstack server {full_name}") from err
github_runner_manager.errors.OpenStackError: Timeout creating openstack server test-dw9uw2ut-0-1cc2b8888ea8

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 276, in _spawn_runners
    return (RunnerManager._create_runner(create_runner_args_sequence[0]),)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 404, in _create_runner
    return args.cloud_runner_manager.create_runner(registration_token=args.registration_token)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 212, in create_runner
    raise RunnerCreateError(f"Failed to create {instance_name} openstack runner") from err
github_runner_manager.errors.RunnerCreateError: Failed to create test-dw9uw2ut-0-1cc2b8888ea8 openstack runner
unit-test-dw9uw2ut-0: 06:50:23 ERROR unit.test-dw9uw2ut/0.juju-log Timeout creating openstack server test-dw9uw2ut-0-1dc0a3462dfc
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1021, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1142, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/utils.py", line 73, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.
unit-test-dw9uw2ut-0: 06:50:25 ERROR unit.test-dw9uw2ut/0.juju-log Failed to spawn a runner.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1021, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/cloud/_compute.py", line 1142, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/openstack/utils.py", line 73, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 204, in create_runner
    instance = self._openstack_cloud.launch_instance(
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 246, in launch_instance
    raise OpenStackError(f"Timeout creating openstack server {full_name}") from err
github_runner_manager.errors.OpenStackError: Timeout creating openstack server test-dw9uw2ut-0-1dc0a3462dfc

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 276, in _spawn_runners
    return (RunnerManager._create_runner(create_runner_args_sequence[0]),)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 404, in _create_runner
    return args.cloud_runner_manager.create_runner(registration_token=args.registration_token)
  File "/var/lib/juju/agents/unit-test-dw9uw2ut-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 212, in create_runner
    raise RunnerCreateError(f"Failed to create {instance_name} openstack runner") from err
github_runner_manager.errors.RunnerCreateError: Failed to create test-dw9uw2ut-0-1dc0a3462dfc openstack runner
unit-test-dw9uw2ut-0: 06:51:51 CRITICAL unit.test-dw9uw2ut/0.juju-log test mode is enabled
unit-test-dw9uw2ut-0: 06:51:54 CRITICAL unit.test-dw9uw2ut/0.juju-log test mode is enabled
unit-test-dw9uw2ut-0: 06:51:55 ERROR juju.worker.uniter resolver loop error: executing operation "run action 2" for test-dw9uw2ut/0: action "juju-exec" (via unknown/invalid hook handler) failed: BSONObj size: 18340974 (0x117DC6E) is invalid. Size must be between 0 and 16793600(16MB) First element: update: "actions"
unit-test-dw9uw2ut-0: 06:51:55 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: executing operation "run action 2" for test-dw9uw2ut/0: action "juju-exec" (via unknown/invalid hook handler) failed: BSONObj size: 18340974 (0x117DC6E) is invalid. Size must be between 0 and 16793600(16MB) First element: update: "actions"

INFO     pytest_operator.plugin:plugin.py:1017 Forgetting model main...