INFO     github_runner_manager.manager.runner_manager:runner_manager.py:132 Creating 1 runners
INFO     github_runner_manager.openstack_cloud.openstack_cloud:openstack_cloud.py:220 Creating openstack server with test-yey460kp-0-5462640ac2db
WARNING  github_runner_manager.openstack_cloud.openstack_cloud:openstack_cloud.py:349 Unable to SSH into test-yey460kp-0-5462640ac2db with address 10.145.193.36
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 338, in get_ssh_connection
    result = connection.run(f"echo {_TEST_STRING}", warn=True, timeout=_SSH_TIMEOUT)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.145.193.36
WARNING  github_runner_manager.openstack_cloud.openstack_runner_manager:utilities.py:88 Retrying error in 60 seconds: Failed to SSH to test-yey460kp-0-5462640ac2db during creation possible due to setup not completed
INFO     paramiko.transport:transport.py:1944 Connected (version 2.0, client OpenSSH_9.6p1)
INFO     paramiko.transport:transport.py:1944 Authentication (publickey) failed.
WARNING  github_runner_manager.openstack_cloud.openstack_cloud:openstack_cloud.py:349 Unable to SSH into test-yey460kp-0-5462640ac2db with address 10.145.193.36
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 338, in get_ssh_connection
    result = connection.run(f"echo {_TEST_STRING}", warn=True, timeout=_SSH_TIMEOUT)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 730, in _auth
    key = self._key_from_filepath(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 435, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/ed25519key.py", line 60, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 543, in _read_private_key
    raise SSHException(
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key
WARNING  github_runner_manager.openstack_cloud.openstack_runner_manager:utilities.py:88 Retrying error in 60 seconds: Failed to SSH to test-yey460kp-0-5462640ac2db during creation possible due to setup not completed
INFO     paramiko.transport:transport.py:1944 Connected (version 2.0, client OpenSSH_9.6p1)
INFO     paramiko.transport:transport.py:1944 Authentication (publickey) failed.
WARNING  github_runner_manager.openstack_cloud.openstack_cloud:openstack_cloud.py:349 Unable to SSH into test-yey460kp-0-5462640ac2db with address 10.145.193.36
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 338, in get_ssh_connection
    result = connection.run(f"echo {_TEST_STRING}", warn=True, timeout=_SSH_TIMEOUT)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 730, in _auth
    key = self._key_from_filepath(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 435, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/ed25519key.py", line 60, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 543, in _read_private_key
    raise SSHException(
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key
WARNING  github_runner_manager.openstack_cloud.openstack_runner_manager:utilities.py:88 Retrying error in 60 seconds: Failed to SSH to test-yey460kp-0-5462640ac2db during creation possible due to setup not completed
INFO     paramiko.transport:transport.py:1944 Connected (version 2.0, client OpenSSH_9.6p1)
INFO     paramiko.transport:transport.py:1944 Authentication (publickey) failed.
WARNING  github_runner_manager.openstack_cloud.openstack_cloud:openstack_cloud.py:349 Unable to SSH into test-yey460kp-0-5462640ac2db with address 10.145.193.36
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 338, in get_ssh_connection
    result = connection.run(f"echo {_TEST_STRING}", warn=True, timeout=_SSH_TIMEOUT)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 730, in _auth
    key = self._key_from_filepath(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 435, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/ed25519key.py", line 60, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 543, in _read_private_key
    raise SSHException(
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key
WARNING  github_runner_manager.openstack_cloud.openstack_runner_manager:utilities.py:88 Retrying error in 60 seconds: Failed to SSH to test-yey460kp-0-5462640ac2db during creation possible due to setup not completed
INFO     paramiko.transport:transport.py:1944 Connected (version 2.0, client OpenSSH_9.6p1)
INFO     paramiko.transport:transport.py:1944 Authentication (publickey) failed.
WARNING  github_runner_manager.openstack_cloud.openstack_cloud:openstack_cloud.py:349 Unable to SSH into test-yey460kp-0-5462640ac2db with address 10.145.193.36
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 338, in get_ssh_connection
    result = connection.run(f"echo {_TEST_STRING}", warn=True, timeout=_SSH_TIMEOUT)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 730, in _auth
    key = self._key_from_filepath(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 435, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/ed25519key.py", line 60, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 543, in _read_private_key
    raise SSHException(
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key
WARNING  github_runner_manager.openstack_cloud.openstack_runner_manager:utilities.py:88 Retrying error in 60 seconds: Failed to SSH to test-yey460kp-0-5462640ac2db during creation possible due to setup not completed
INFO     paramiko.transport:transport.py:1944 Connected (version 2.0, client OpenSSH_9.6p1)
INFO     paramiko.transport:transport.py:1944 Authentication (publickey) failed.
WARNING  github_runner_manager.openstack_cloud.openstack_cloud:openstack_cloud.py:349 Unable to SSH into test-yey460kp-0-5462640ac2db with address 10.145.193.36
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 338, in get_ssh_connection
    result = connection.run(f"echo {_TEST_STRING}", warn=True, timeout=_SSH_TIMEOUT)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 730, in _auth
    key = self._key_from_filepath(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 435, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/ed25519key.py", line 60, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 543, in _read_private_key
    raise SSHException(
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key
WARNING  github_runner_manager.openstack_cloud.openstack_runner_manager:utilities.py:88 Retrying error in 60 seconds: Failed to SSH to test-yey460kp-0-5462640ac2db during creation possible due to setup not completed
INFO     paramiko.transport:transport.py:1944 Connected (version 2.0, client OpenSSH_9.6p1)
INFO     paramiko.transport:transport.py:1944 Authentication (publickey) failed.
WARNING  github_runner_manager.openstack_cloud.openstack_cloud:openstack_cloud.py:349 Unable to SSH into test-yey460kp-0-5462640ac2db with address 10.145.193.36
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 338, in get_ssh_connection
    result = connection.run(f"echo {_TEST_STRING}", warn=True, timeout=_SSH_TIMEOUT)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 730, in _auth
    key = self._key_from_filepath(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 435, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/ed25519key.py", line 60, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 543, in _read_private_key
    raise SSHException(
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key
WARNING  github_runner_manager.openstack_cloud.openstack_runner_manager:utilities.py:88 Retrying error in 60 seconds: Failed to SSH to test-yey460kp-0-5462640ac2db during creation possible due to setup not completed
INFO     paramiko.transport:transport.py:1944 Connected (version 2.0, client OpenSSH_9.6p1)
INFO     paramiko.transport:transport.py:1944 Authentication (publickey) failed.
WARNING  github_runner_manager.openstack_cloud.openstack_cloud:openstack_cloud.py:349 Unable to SSH into test-yey460kp-0-5462640ac2db with address 10.145.193.36
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 338, in get_ssh_connection
    result = connection.run(f"echo {_TEST_STRING}", warn=True, timeout=_SSH_TIMEOUT)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 730, in _auth
    key = self._key_from_filepath(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 435, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/ed25519key.py", line 60, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 543, in _read_private_key
    raise SSHException(
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key
WARNING  github_runner_manager.openstack_cloud.openstack_runner_manager:utilities.py:88 Retrying error in 60 seconds: Failed to SSH to test-yey460kp-0-5462640ac2db during creation possible due to setup not completed
INFO     paramiko.transport:transport.py:1944 Connected (version 2.0, client OpenSSH_9.6p1)
INFO     paramiko.transport:transport.py:1944 Authentication (publickey) failed.
WARNING  github_runner_manager.openstack_cloud.openstack_cloud:openstack_cloud.py:349 Unable to SSH into test-yey460kp-0-5462640ac2db with address 10.145.193.36
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 338, in get_ssh_connection
    result = connection.run(f"echo {_TEST_STRING}", warn=True, timeout=_SSH_TIMEOUT)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 730, in _auth
    key = self._key_from_filepath(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 435, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/ed25519key.py", line 60, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 543, in _read_private_key
    raise SSHException(
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key
WARNING  github_runner_manager.openstack_cloud.openstack_runner_manager:utilities.py:88 Retrying error in 60 seconds: Failed to SSH to test-yey460kp-0-5462640ac2db during creation possible due to setup not completed
INFO     paramiko.transport:transport.py:1944 Connected (version 2.0, client OpenSSH_9.6p1)
INFO     paramiko.transport:transport.py:1944 Authentication (publickey) failed.
WARNING  github_runner_manager.openstack_cloud.openstack_cloud:openstack_cloud.py:349 Unable to SSH into test-yey460kp-0-5462640ac2db with address 10.145.193.36
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 338, in get_ssh_connection
    result = connection.run(f"echo {_TEST_STRING}", warn=True, timeout=_SSH_TIMEOUT)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 730, in _auth
    key = self._key_from_filepath(
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 435, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/ed25519key.py", line 60, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/paramiko/pkey.py", line 543, in _read_private_key
    raise SSHException(
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key
ERROR    github_runner_manager.openstack_cloud.openstack_runner_manager:utilities.py:84 Retry limit of 10 exceed: Failed to SSH to test-yey460kp-0-5462640ac2db during creation possible due to setup not completed
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 644, in _wait_runner_startup
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 356, in get_ssh_connection
    raise SSHError(
github_runner_manager.errors.SSHError: No connectable SSH addresses found, server: test-yey460kp-0-5462640ac2db, addresses: ['10.145.193.36']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 646, in _wait_runner_startup
    raise RunnerStartError(
github_runner_manager.errors.RunnerStartError: Failed to SSH to test-yey460kp-0-5462640ac2db during creation possible due to setup not completed
ERROR    github_runner_manager.manager.runner_manager:runner_manager.py:278 Failed to spawn a runner.
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 644, in _wait_runner_startup
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_cloud.py", line 356, in get_ssh_connection
    raise SSHError(
github_runner_manager.errors.SSHError: No connectable SSH addresses found, server: test-yey460kp-0-5462640ac2db, addresses: ['10.145.193.36']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/manager/runner_manager.py", line 276, in _spawn_runners
    return (RunnerManager._create_runner(create_runner_args_sequence[0]),)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/manager/runner_manager.py", line 404, in _create_runner
    return args.cloud_runner_manager.create_runner(registration_token=args.registration_token)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 220, in create_runner
    self._wait_runner_startup(instance)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/home/ubuntu/actions-runner/_work/github-runner-operator/github-runner-operator/.tox/integration-juju3.6/lib/python3.10/site-packages/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 646, in _wait_runner_startup
    raise RunnerStartError(
github_runner_manager.errors.RunnerStartError: Failed to SSH to test-yey460kp-0-5462640ac2db during creation possible due to setup not completed