INFO     pytest_operator.plugin:plugin.py:929 Model status:

Model                   Controller  Cloud/Region         Version  SLA          Timestamp
test-charm-runner-y32m  lxd         localhost/localhost  3.6.1    unsupported  20:54:10Z

App                          Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active      1  github-runner-image-builder  latest/edge    2  no       
test-vc24xrsc                         active      1  github-runner                               0  no       

Unit                            Workload  Agent  Machine  Public address  Ports  Message
github-runner-image-builder/0*  active    idle   0        10.122.232.225         
test-vc24xrsc/0*                active    idle   1        10.122.232.207         

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.122.232.225  juju-5e8e32-0  ubuntu@22.04      Running
1        started  10.122.232.207  juju-5e8e32-1  ubuntu@22.04      Running

INFO     pytest_operator.plugin:plugin.py:935 Juju error logs:

machine-0: 20:47:14 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 20:47:14 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-0: 20:47:14 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 20:50:28 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 20:50:28 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-vc24xrsc-0: 20:50:28 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-test-vc24xrsc-0: 20:50:41 CRITICAL unit.test-vc24xrsc/0.juju-log test mode is enabled
unit-test-vc24xrsc-0: 20:50:43 CRITICAL unit.test-vc24xrsc/0.juju-log test mode is enabled
unit-test-vc24xrsc-0: 20:50:46 CRITICAL unit.test-vc24xrsc/0.juju-log image:0: test mode is enabled
unit-test-vc24xrsc-0: 20:50:47 CRITICAL unit.test-vc24xrsc/0.juju-log test mode is enabled
unit-test-vc24xrsc-0: 20:50:48 CRITICAL unit.test-vc24xrsc/0.juju-log test mode is enabled
unit-test-vc24xrsc-0: 20:50:50 CRITICAL unit.test-vc24xrsc/0.juju-log test mode is enabled
unit-test-vc24xrsc-0: 20:50:51 CRITICAL unit.test-vc24xrsc/0.juju-log test mode is enabled
unit-test-vc24xrsc-0: 20:50:52 CRITICAL unit.test-vc24xrsc/0.juju-log image:0: test mode is enabled
unit-test-vc24xrsc-0: 20:50:53 CRITICAL unit.test-vc24xrsc/0.juju-log image:0: test mode is enabled
unit-test-vc24xrsc-0: 20:51:56 CRITICAL unit.test-vc24xrsc/0.juju-log test mode is enabled
unit-test-vc24xrsc-0: 20:51:57 CRITICAL unit.test-vc24xrsc/0.juju-log test mode is enabled
unit-test-vc24xrsc-0: 20:52:13 ERROR unit.test-vc24xrsc/0.juju-log Failed to create openstack server test-vc24xrsc-0-28103550ffc8
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/cloud/_compute.py", line 992, in create_server
    server = self.compute.create_server(**kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/compute/v2/_proxy.py", line 727, in create_server
    return self._create(_server.Server, **attrs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/proxy.py", line 643, in _create
    return res.create(self, base_path=base_path)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/resource.py", line 1533, in create
    self._translate_response(response, **response_kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/resource.py", line 1285, in _translate_response
    exceptions.raise_from_response(response, error_message=error_message)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/exceptions.py", line 247, in raise_from_response
    raise cls(
openstack.exceptions.ForbiddenException: ForbiddenException: 403: Client Error for url: https://nova.ps6.canonical.com:8774/v2.1/servers, Maximum number of ports exceeded
unit-test-vc24xrsc-0: 20:52:13 ERROR unit.test-vc24xrsc/0.juju-log Failed to spawn a runner.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/cloud/_compute.py", line 992, in create_server
    server = self.compute.create_server(**kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/compute/v2/_proxy.py", line 727, in create_server
    return self._create(_server.Server, **attrs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/proxy.py", line 643, in _create
    return res.create(self, base_path=base_path)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/resource.py", line 1533, in create
    self._translate_response(response, **response_kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/resource.py", line 1285, in _translate_response
    exceptions.raise_from_response(response, error_message=error_message)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/exceptions.py", line 247, in raise_from_response
    raise cls(
openstack.exceptions.ForbiddenException: ForbiddenException: 403: Client Error for url: https://nova.ps6.canonical.com:8774/v2.1/servers, Maximum number of ports exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 209, in create_runner
    instance = self._openstack_cloud.launch_instance(
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 250, in launch_instance
    raise OpenStackError(f"Failed to create openstack server {full_name}") from err
github_runner_manager.errors.OpenStackError: Failed to create openstack server test-vc24xrsc-0-28103550ffc8

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 276, in _spawn_runners
    return (RunnerManager._create_runner(create_runner_args_sequence[0]),)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 404, in _create_runner
    return args.cloud_runner_manager.create_runner(registration_token=args.registration_token)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 217, in create_runner
    raise RunnerCreateError(f"Failed to create {instance_name} openstack runner") from err
github_runner_manager.errors.RunnerCreateError: Failed to create test-vc24xrsc-0-28103550ffc8 openstack runner
unit-test-vc24xrsc-0: 20:52:19 CRITICAL unit.test-vc24xrsc/0.juju-log test mode is enabled
unit-test-vc24xrsc-0: 20:52:37 ERROR unit.test-vc24xrsc/0.juju-log Failed to create openstack server test-vc24xrsc-0-9ffb026bc5e9
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/cloud/_compute.py", line 992, in create_server
    server = self.compute.create_server(**kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/compute/v2/_proxy.py", line 727, in create_server
    return self._create(_server.Server, **attrs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/proxy.py", line 643, in _create
    return res.create(self, base_path=base_path)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/resource.py", line 1533, in create
    self._translate_response(response, **response_kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/resource.py", line 1285, in _translate_response
    exceptions.raise_from_response(response, error_message=error_message)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/exceptions.py", line 247, in raise_from_response
    raise cls(
openstack.exceptions.ForbiddenException: ForbiddenException: 403: Client Error for url: https://nova.ps6.canonical.com:8774/v2.1/servers, Maximum number of ports exceeded
unit-test-vc24xrsc-0: 20:52:38 ERROR unit.test-vc24xrsc/0.juju-log Failed to spawn a runner.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/cloud/_compute.py", line 992, in create_server
    server = self.compute.create_server(**kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/compute/v2/_proxy.py", line 727, in create_server
    return self._create(_server.Server, **attrs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/proxy.py", line 643, in _create
    return res.create(self, base_path=base_path)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/resource.py", line 1533, in create
    self._translate_response(response, **response_kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/resource.py", line 1285, in _translate_response
    exceptions.raise_from_response(response, error_message=error_message)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/openstack/exceptions.py", line 247, in raise_from_response
    raise cls(
openstack.exceptions.ForbiddenException: ForbiddenException: 403: Client Error for url: https://nova.ps6.canonical.com:8774/v2.1/servers, Maximum number of ports exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 209, in create_runner
    instance = self._openstack_cloud.launch_instance(
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 250, in launch_instance
    raise OpenStackError(f"Failed to create openstack server {full_name}") from err
github_runner_manager.errors.OpenStackError: Failed to create openstack server test-vc24xrsc-0-9ffb026bc5e9

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 276, in _spawn_runners
    return (RunnerManager._create_runner(create_runner_args_sequence[0]),)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 404, in _create_runner
    return args.cloud_runner_manager.create_runner(registration_token=args.registration_token)
  File "/var/lib/juju/agents/unit-test-vc24xrsc-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 217, in create_runner
    raise RunnerCreateError(f"Failed to create {instance_name} openstack runner") from err
github_runner_manager.errors.RunnerCreateError: Failed to create test-vc24xrsc-0-9ffb026bc5e9 openstack runner
unit-test-vc24xrsc-0: 20:52:59 CRITICAL unit.test-vc24xrsc/0.juju-log test mode is enabled
unit-test-vc24xrsc-0: 20:53:06 CRITICAL unit.test-vc24xrsc/0.juju-log test mode is enabled
unit-test-vc24xrsc-0: 20:53:07 CRITICAL unit.test-vc24xrsc/0.juju-log test mode is enabled
unit-test-vc24xrsc-0: 20:53:28 CRITICAL unit.test-vc24xrsc/0.juju-log test mode is enabled

INFO     pytest_operator.plugin:plugin.py:1017 Forgetting model main...