INFO     pytest_operator.plugin:plugin.py:929 Model status:

Model                            Controller  Cloud/Region         Version  SLA          Timestamp
test-charm-metrics-success-5b7f  lxd         localhost/localhost  3.6.1    unsupported  07:57:49Z

App                          Version  Status   Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active       1  github-runner-image-builder  latest/edge    2  no       
test-xnv7izzh                         blocked      1  github-runner                               0  no       Invalid token.

Unit                            Workload  Agent  Machine  Public address  Ports  Message
github-runner-image-builder/0*  active    idle   0        10.80.213.3            
test-xnv7izzh/0*                blocked   idle   1        10.80.213.68           Invalid token.

Machine  State    Address       Inst id        Base          AZ  Message
0        started  10.80.213.3   juju-73fb6a-0  ubuntu@22.04      Running
1        started  10.80.213.68  juju-73fb6a-1  ubuntu@22.04      Running

INFO     pytest_operator.plugin:plugin.py:935 Juju error logs:

machine-0: 06:25:29 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 06:25:30 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-0: 06:25:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 06:28:44 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 06:28:44 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-xnv7izzh-0: 06:28:44 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-test-xnv7izzh-0: 06:28:59 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 06:29:01 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 06:29:05 CRITICAL unit.test-xnv7izzh/0.juju-log image:0: test mode is enabled
unit-test-xnv7izzh-0: 06:29:05 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 06:29:06 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 06:29:08 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 06:29:09 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 06:29:10 CRITICAL unit.test-xnv7izzh/0.juju-log image:0: test mode is enabled
unit-test-xnv7izzh-0: 06:29:11 CRITICAL unit.test-xnv7izzh/0.juju-log image:0: test mode is enabled
unit-test-xnv7izzh-0: 06:29:12 ERROR unit.test-xnv7izzh/0.juju-log image:0: Issue with GitHub token
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/github_runner_manager/github_client.py", line 64, in wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/github_runner_manager/github_client.py", line 105, in get_runner_github_info
    self._client.actions.list_self_hosted_runners_for_repo(
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/ghapi/core.py", line 74, in __call__
    return self.client(self.path, self.verb, headers=headers, decode=self.decode, route=route_p, query=query_p, data=data_p)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/ghapi/core.py", line 133, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, decode=decode, debug=debug, return_headers=True,
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/fastcore/net.py", line 221, in urlsend
    return urlread(req, decode=decode, return_json=return_json, return_headers=return_headers, timeout=timeout)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/fastcore/net.py", line 122, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp, msg=e.msg) from None
fastcore.net.HTTP401UnauthorizedError: HTTP Error 401: Unauthorized
====Error Body====
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
}


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/./src/charm.py", line 155, in func_with_catch_errors
    func(self, event)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/./src/charm.py", line 1282, in _on_image_relation_changed
    runner_scaler.flush(flush_mode=FlushMode.FLUSH_IDLE)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/github_runner_manager/manager/runner_scaler.py", line 147, in flush
    metric_stats = self._manager.cleanup()
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 248, in cleanup
    self._github.delete_runners([GitHubRunnerState.OFFLINE])
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/github_runner_manager/manager/github_runner_manager.py", line 93, in delete_runners
    runner_list = self.get_runners(states)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/github_runner_manager/manager/github_runner_manager.py", line 74, in get_runners
    runner_list = self.github.get_runner_github_info(self._path)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/github_runner_manager/github_client.py", line 71, in wrapper
    raise TokenError(msg) from exc
github_runner_manager.errors.TokenError: Invalid token.
unit-test-xnv7izzh-0: 06:33:35 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 06:38:43 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 06:43:09 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 06:48:14 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 06:52:20 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 06:56:59 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:01:47 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:06:05 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:10:42 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:15:16 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:19:46 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:24:43 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:30:18 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:32:38 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:32:39 ERROR unit.test-xnv7izzh/0.juju-log Issue with GitHub token
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/github_runner_manager/github_client.py", line 64, in wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/github_runner_manager/github_client.py", line 105, in get_runner_github_info
    self._client.actions.list_self_hosted_runners_for_repo(
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/ghapi/core.py", line 74, in __call__
    return self.client(self.path, self.verb, headers=headers, decode=self.decode, route=route_p, query=query_p, data=data_p)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/ghapi/core.py", line 133, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, decode=decode, debug=debug, return_headers=True,
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/fastcore/net.py", line 221, in urlsend
    return urlread(req, decode=decode, return_json=return_json, return_headers=return_headers, timeout=timeout)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/fastcore/net.py", line 122, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp, msg=e.msg) from None
fastcore.net.HTTP401UnauthorizedError: HTTP Error 401: Unauthorized
====Error Body====
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
}


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/./src/charm.py", line 155, in func_with_catch_errors
    func(self, event)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/./src/charm.py", line 757, in _on_reconcile_runners
    self._trigger_reconciliation()
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/./src/charm.py", line 778, in _trigger_reconciliation
    self._reconcile_openstack_runners(runner_scaler, state.runner_config.virtual_machines)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/./src/charm.py", line 1009, in _reconcile_openstack_runners
    runner_scaler.reconcile(num)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/github_runner_manager/manager/runner_scaler.py", line 195, in reconcile
    runner_list = self._manager.get_runners()
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 159, in get_runners
    github_infos = self._github.get_runners(github_states)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/github_runner_manager/manager/github_runner_manager.py", line 74, in get_runners
    runner_list = self.github.get_runner_github_info(self._path)
  File "/var/lib/juju/agents/unit-test-xnv7izzh-0/charm/venv/github_runner_manager/github_client.py", line 71, in wrapper
    raise TokenError(msg) from exc
github_runner_manager.errors.TokenError: Invalid token.
unit-test-xnv7izzh-0: 07:34:44 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:39:24 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:45:08 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:49:09 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:53:24 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled
unit-test-xnv7izzh-0: 07:57:28 CRITICAL unit.test-xnv7izzh/0.juju-log test mode is enabled

INFO     pytest_operator.plugin:plugin.py:1017 Forgetting model main...