06:49:14 INFO GitHub token rate limit: Rate(reset=2025-05-03 07:24:32+00:00, remaining=4673, limit=5000)
06:53:56 INFO Waiting for model:
  test-yoeg555x/0 [executing] maintenance: Reconciling runners
06:54:26 INFO Waiting for model:
  test-yoeg555x/0 [idle] active: 
06:54:40 INFO Wait for condition not met, sleeping 10
06:55:29 INFO Waiting for model:
  test-yoeg555x/0 [executing] active: 
06:55:59 INFO Waiting for model:
  test-yoeg555x/0 [idle] active: 
06:56:02 INFO File content of /var/log/github-runner-metrics.log: {"timestamp": 1746255206.0, "event": "runner_installed", "flavor": "test-yoeg555x", "duration": 230.0}
{"timestamp": 1746255284.0, "event": "runner_start", "flavor": "test-yoeg555x", "workflow": "Workflow Dispatch Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "idle": 78.0, "queue_duration": 2.0}
{"timestamp": 1746255287.0, "event": "runner_stop", "flavor": "test-yoeg555x", "workflow": "Workflow Dispatch Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "status": "normal", "job_duration": 3.0, "job_conclusion": "success"}
{"timestamp": 1746255328.2755363, "event": "reconciliation", "flavor": "test-yoeg555x", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 33.54639482498169}
{"timestamp": 1746255345.221794, "event": "reconciliation", "flavor": "test-yoeg555x", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 15.55679702758789}
06:56:04 INFO Model status:

Model                            Controller           Cloud/Region         Version  SLA          Timestamp
test-charm-metrics-success-csm4  github-pr-b51b1-lxd  localhost/localhost  3.6.5    unsupported  06:56:04Z

App                                   Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder-yoeg555x           active      1  github-runner-image-builder  latest/edge   68  no       
test-yoeg555x                                  active      1  github-runner                               0  no       

Unit                                     Workload  Agent  Machine  Public address  Ports  Message
github-runner-image-builder-yoeg555x/0*  active    idle   0        10.32.40.251           
test-yoeg555x/0*                         active    idle   1        10.32.40.197           

Machine  State    Address       Inst id        Base          AZ  Message
0        started  10.32.40.251  juju-3927da-0  ubuntu@22.04      Running
1        started  10.32.40.197  juju-3927da-1  ubuntu@22.04      Running

06:56:04 INFO Juju error logs:

machine-0: 06:26:05 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 06:26:05 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-yoeg555x-0: 06:26:06 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 06:26:16 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 06:26:16 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-yoeg555x-0: 06:26:16 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-github-runner-image-builder-yoeg555x-0: 06:26:53 ERROR unit.github-runner-image-builder-yoeg555x/0.juju-log Pipx command failed, code: 1, out: None, err: None
unit-test-yoeg555x-0: 06:27:02 ERROR unit.test-yoeg555x/0.juju-log Command python3 -m pip uninstall github_runner_manager failed with code 2: b'ERROR: Exception:\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper\n    status = _inner_run()\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run\n    return self.run(options, args)\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/uninstall.py", line 106, in run\n    uninstall_pathset = req.uninstall(\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_install.py", line 723, in uninstall\n    uninstalled_pathset.remove(auto_confirm, verbose)\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_uninstall.py", line 364, in remove\n    if auto_confirm or self._allowed_to_proceed(verbose):\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_uninstall.py", line 404, in _allowed_to_proceed\n    return ask("Proceed (Y/n)? ", ("y", "n", "")) != "n"\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/misc.py", line 229, in ask\n    response = input(message)\nEOFError: EOF when reading a line\n'
unit-test-yoeg555x-0: 06:48:25 ERROR unit.test-yoeg555x/0.juju-log Unable to get SSH connection for instance test-yoeg555x-0-n-44b88b3ae14e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-yoeg555x-0-n-44b88b3ae14e, key path: /home/runner-manager/.ssh/test-yoeg555x-0-n-44b88b3ae14e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-yoeg555x-0-n-44b88b3ae14e
unit-test-yoeg555x-0: 06:48:31 ERROR unit.test-yoeg555x/0.juju-log Unable to get SSH connection for instance test-yoeg555x-0-n-44b88b3ae14e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-yoeg555x-0-n-44b88b3ae14e, key path: /home/runner-manager/.ssh/test-yoeg555x-0-n-44b88b3ae14e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-yoeg555x-0-n-44b88b3ae14e
unit-test-yoeg555x-0: 06:48:35 ERROR unit.test-yoeg555x/0.juju-log Unable to get SSH connection for instance test-yoeg555x-0-n-44b88b3ae14e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-yoeg555x-0-n-44b88b3ae14e, key path: /home/runner-manager/.ssh/test-yoeg555x-0-n-44b88b3ae14e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-yoeg555x-0-n-44b88b3ae14e
unit-test-yoeg555x-0: 06:48:35 ERROR unit.test-yoeg555x/0.juju-log Failed to get SSH connection while removing test-yoeg555x-0-n-44b88b3ae14e
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 311, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-yoeg555x-0-n-44b88b3ae14e, key path: /home/runner-manager/.ssh/test-yoeg555x-0-n-44b88b3ae14e.key
unit-test-yoeg555x-0: 06:48:38 ERROR unit.test-yoeg555x/0.juju-log Invalid pulled metrics. No runner_installed information for test-yoeg555x-0-n-44b88b3ae14e.
unit-test-yoeg555x-0: 06:48:38 ERROR unit.test-yoeg555x/0.juju-log No metrics returned after deleting test-yoeg555x-0-n-44b88b3ae14e
unit-test-yoeg555x-0: 06:48:44 ERROR unit.test-yoeg555x/0.juju-log Unable to get SSH connection for instance test-yoeg555x-0-n-44b88b3ae14e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-yoeg555x-0-n-44b88b3ae14e, key path: /home/runner-manager/.ssh/test-yoeg555x-0-n-44b88b3ae14e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-yoeg555x-0-n-44b88b3ae14e
unit-test-yoeg555x-0: 06:48:48 ERROR unit.test-yoeg555x/0.juju-log Unable to get SSH connection for instance test-yoeg555x-0-n-44b88b3ae14e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-yoeg555x-0-n-44b88b3ae14e, key path: /home/runner-manager/.ssh/test-yoeg555x-0-n-44b88b3ae14e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-yoeg555x-0-n-44b88b3ae14e
unit-test-yoeg555x-0: 06:48:51 ERROR unit.test-yoeg555x/0.juju-log Failed to get SSH connection while removing test-yoeg555x-0-n-44b88b3ae14e
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 311, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-yoeg555x-0-n-44b88b3ae14e, key path: /home/runner-manager/.ssh/test-yoeg555x-0-n-44b88b3ae14e.key
unit-test-yoeg555x-0: 06:48:53 ERROR unit.test-yoeg555x/0.juju-log Invalid pulled metrics. No runner_installed information for test-yoeg555x-0-n-44b88b3ae14e.
unit-test-yoeg555x-0: 06:55:17 ERROR unit.test-yoeg555x/0.juju-log Unable to get SSH connection for instance test-yoeg555x-0-n-26c3a92b6cb5, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-yoeg555x-0-n-26c3a92b6cb5, key path: /home/runner-manager/.ssh/test-yoeg555x-0-n-26c3a92b6cb5.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-yoeg555x-0-n-26c3a92b6cb5
unit-test-yoeg555x-0: 06:55:20 ERROR unit.test-yoeg555x/0.juju-log Unable to get SSH connection for instance test-yoeg555x-0-n-26c3a92b6cb5, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-yoeg555x-0-n-26c3a92b6cb5, key path: /home/runner-manager/.ssh/test-yoeg555x-0-n-26c3a92b6cb5.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-yoeg555x-0-n-26c3a92b6cb5
unit-test-yoeg555x-0: 06:55:23 ERROR unit.test-yoeg555x/0.juju-log Failed to get SSH connection while removing test-yoeg555x-0-n-26c3a92b6cb5
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 311, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-yoeg555x-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-yoeg555x-0-n-26c3a92b6cb5, key path: /home/runner-manager/.ssh/test-yoeg555x-0-n-26c3a92b6cb5.key
unit-test-yoeg555x-0: 06:55:25 ERROR unit.test-yoeg555x/0.juju-log Invalid pulled metrics. No runner_installed information for test-yoeg555x-0-n-26c3a92b6cb5.

06:56:04 INFO Forgetting model main...